
// export const Dashboard = lazy(()=>import("./pages/Admin/Dashboard"))
// export const Customers = lazy(()=>import("./pages/Admin/Customers"))
// export const Transaction = lazy(()=>import("./pages/Admin/Transaction"))
// export const Products = lazy(()=>import("./pages/Admin/Products"))
// export const NewProduct = lazy(()=>import("./pages/Admin/management/NewProduct"))
// export const ProductManagement = lazy(()=>import("./pages/Admin/management/ProductManagement"))
// export const TransactionManagement = lazy(()=>import("./pages/Admin/management/TransactionManagement"))
// export const BarCharts = lazy(()=>import("./pages/Admin/charts/BarCharts"))
// export const PieCharts = lazy(()=>import("./pages/Admin/charts/PieCharts"))
// export const LineCharts = lazy(()=>import("./pages/Admin/charts/LineCharts"))
// export const Stopwatch = lazy(()=>import("./pages/Admin/apps/Stopwatch"))
// export const Toss = lazy(()=>import("./pages/Admin/apps/Toss"))
// export const Coupon = lazy(()=>import("./pages/Admin/apps/Coupon"))